In [12]:
from os import fsencode, listdir, fsdecode
from math import inf

import cv2
import imutils
import numpy as np

directory = fsencode('input')
for file in listdir(directory)[:1]:
    filename = fsdecode(file)
    image = cv2.imread('input/' + filename)
    ratio = image.shape[0] / 300.0
    orig = image.copy()
    image = imutils.resize(image, height=300)
    edged = cv2.Canny(image, 0, 200)
    (returned_edged, contours, hierarchy) = cv2.findContours(edged.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    largest_contours = sorted(contours, key=cv2.contourArea, reverse=True)[:10]
    image_contour = None
    for c in largest_contours:
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.02 * peri, True)
        if len(approx) == 4:
            image_contour = approx
            break
    # print (image_contour)
    # max_x = 0
    # max_y = 0
    # min_x = inf
    # min_y = inf
    # for point_array in image_contour:
    #     point = point_array[0]
    #     if point[0] > max_x:
    #         max_x = point[0]
    #     if point[1] > max_y:
    #         max_y = point[1]
    #     if point[0] < min_x:
    #         min_x = point[0]
    #     if point[1] < min_y:
    #         min_y = point[1]
    # print(min_x * ratio, min_y * ratio, max_x * ratio, max_y * ratio)

[[[ 62  10]]

 [[421   8]]

 [[425 259]]

 [[ 64 260]]]
714.24 92.16 4896.0 2995.2
